/**
 * Builds the existing React + Three.js game (in the repo root) and copies the
 * production output into this Expo project's assets so it can be bundled and
 * loaded locally by the WebView.
 *
 * The game already uses vite-plugin-singlefile, so JS + CSS are inlined into a
 * single index.html. External references that remain are:
 *   - public/images/* JPGs  → inlined as base64 data URIs
 *   - public/fonts/* woff2  → inlined as base64 data URIs (CSS inlined too)
 * The resulting index.html is fully self-contained and loadable from a file://
 * URI inside react-native-webview. 100% offline capable.
 *
 * Run from the android-app directory:  node scripts/build-game.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const GAME_DIST = path.join(ROOT, 'dist');
const OUT_DIR = path.resolve(__dirname, '..', 'src');
const OUT_FILE = path.join(OUT_DIR, 'gameBundle.ts');

function log(msg) {
  process.stdout.write(`[build-game] ${msg}\n`);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function inlineImages(html) {
  const imagesDir = path.join(GAME_DIST, 'images');
  if (!fs.existsSync(imagesDir)) {
    log('No dist/images directory found — nothing to inline.');
    return html;
  }
  let out = html;
  for (const file of fs.readdirSync(imagesDir)) {
    if (!/\.(jpg|jpeg|png|gif|webp|svg)$/i.test(file)) continue;
    const abs = path.join(imagesDir, file);
    const buf = fs.readFileSync(abs);
    const ext = path.extname(file).slice(1).toLowerCase().replace('jpeg', 'jpg');
    const mime = ext === 'svg' ? 'image/svg+xml' : `image/${ext}`;
    const dataUri = `data:${mime};base64,${buf.toString('base64')}`;
    // The game references images as absolute paths: /images/ui_menu_hero.jpg
    const token = `/images/${file}`;
    const before = out;
    out = out.split(token).join(dataUri);
    if (out !== before) log(`Inlined /images/${file} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
  return out;
}

function inlineFonts(html) {
  const fontsCssPath = path.join(GAME_DIST, 'fonts', 'fonts.css');
  if (!fs.existsSync(fontsCssPath)) {
    log('No dist/fonts/fonts.css found — skipping font inlining.');
    return html;
  }
  let css = fs.readFileSync(fontsCssPath, 'utf8');
  const fontsDir = path.join(GAME_DIST, 'fonts');
  // Replace each url('/fonts/*.woff2') with a base64 data URI
  for (const file of fs.readdirSync(fontsDir)) {
    if (!file.endsWith('.woff2')) continue;
    const abs = path.join(fontsDir, file);
    const buf = fs.readFileSync(abs);
    const dataUri = `data:font/woff2;base64,${buf.toString('base64')}`;
    const token = `/fonts/${file}`;
    const before = css;
    css = css.split(token).join(dataUri);
    if (css !== before) log(`Inlined /fonts/${file} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
  // Replace the <link rel="stylesheet" href="...fonts/fonts.css" /> with an inline <style>.
  // Vite may emit either /fonts/fonts.css or ./fonts/fonts.css depending on base config.
  const linkTag = /<link\s+rel="stylesheet"\s+href="\.?\/?fonts\/fonts\.css"\s*\/?>/i;
  const before = html;
  html = html.replace(linkTag, `<style>\n${css}\n</style>`);
  if (html === before) log('WARNING: fonts.css <link> tag not found in HTML — fonts may not be inlined.');
  return html;
}

function main() {
  log(`Game root: ${ROOT}`);
  log(`Game dist: ${GAME_DIST}`);

  if (!fs.existsSync(path.join(ROOT, 'package.json'))) {
    throw new Error('Could not find game package.json at repo root.');
  }

  // 1. Build the game.
  log('Running game production build (vite build)...');
  const { execSync } = require('child_process');
  execSync('npm run build', { cwd: ROOT, stdio: 'inherit', env: process.env });

  const distHtml = path.join(GAME_DIST, 'index.html');
  if (!fs.existsSync(distHtml)) {
    throw new Error('vite build did not produce dist/index.html');
  }

  // 2. Inline images so the HTML is fully self-contained.
  log('Inlining image assets as base64 data URIs...');
  let html = fs.readFileSync(distHtml, 'utf8');
  html = inlineImages(html);

  // 3. Inline fonts (CSS + woff2) so no external font requests remain.
  log('Inlining font assets as base64 data URIs...');
  html = inlineFonts(html);

  // 4. Write the self-contained bundle as a TypeScript string export so it
  //    imports directly into the app with no Metro asset config or runtime
  //    file loading. This is the most robust approach across dev/prod/EAS.
  ensureDir(OUT_DIR);
  const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const ts = `// AUTO-GENERATED by scripts/build-game.js — do not edit.\n// The full self-contained game build as a string. Loaded into the WebView.\nexport const GAME_HTML: string = \`\n${escaped}\n\`;\n`;
  fs.writeFileSync(OUT_FILE, ts, 'utf8');
  const kb = (fs.statSync(OUT_FILE).size / 1024).toFixed(1);
  log(`Wrote ${OUT_FILE} (${kb} KB)`);
  log('Done. The game is now bundled locally for the WebView.');
}

try {
  main();
} catch (err) {
  process.stderr.write(`[build-game] FAILED: ${err && err.message ? err.message : err}\n`);
  process.exit(1);
}
