/**
 * Builds the existing React + Three.js game (in the repo root) and copies the
 * production output into this Expo project's assets so it can be bundled and
 * loaded locally by the WebView.
 *
 * The game already uses vite-plugin-singlefile, so JS + CSS are inlined into a
 * single index.html. The only external references are the public/images/* JPGs,
 * which we inline here as base64 data URIs so the resulting index.html is fully
 * self-contained and loadable from a file:// URI inside react-native-webview.
 *
 * Run from the android-app directory:  node scripts/build-game.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const GAME_DIST = path.join(ROOT, 'dist');
const OUT_DIR = path.resolve(__dirname, '..', 'src');
const OUT_FILE = path.join(OUT_DIR, 'gameBundle.ts');

function log(msg) {
  process.stdout.write(`[build-game] ${msg}\n`);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function inlineImages(html) {
  const imagesDir = path.join(GAME_DIST, 'images');
  if (!fs.existsSync(imagesDir)) {
    log('No dist/images directory found — nothing to inline.');
    return html;
  }
  let out = html;
  for (const file of fs.readdirSync(imagesDir)) {
    if (!/\.(jpg|jpeg|png|gif|webp|svg)$/i.test(file)) continue;
    const abs = path.join(imagesDir, file);
    const buf = fs.readFileSync(abs);
    const ext = path.extname(file).slice(1).toLowerCase().replace('jpeg', 'jpg');
    const mime = ext === 'svg' ? 'image/svg+xml' : `image/${ext}`;
    const dataUri = `data:${mime};base64,${buf.toString('base64')}`;
    // The game references images as absolute paths: /images/ui_menu_hero.jpg
    const token = `/images/${file}`;
    const before = out;
    out = out.split(token).join(dataUri);
    if (out !== before) log(`Inlined /images/${file} (${(buf.length / 1024).toFixed(1)} KB)`);
  }
  return out;
}

function main() {
  log(`Game root: ${ROOT}`);
  log(`Game dist: ${GAME_DIST}`);

  if (!fs.existsSync(path.join(ROOT, 'package.json'))) {
    throw new Error('Could not find game package.json at repo root.');
  }

  // 1. Build the game.
  log('Running game production build (vite build)...');
  const { execSync } = require('child_process');
  execSync('npm run build', { cwd: ROOT, stdio: 'inherit', env: process.env });

  const distHtml = path.join(GAME_DIST, 'index.html');
  if (!fs.existsSync(distHtml)) {
    throw new Error('vite build did not produce dist/index.html');
  }

  // 2. Inline images so the HTML is fully self-contained.
  log('Inlining image assets as base64 data URIs...');
  let html = fs.readFileSync(distHtml, 'utf8');
  html = inlineImages(html);

  // 3. Write the self-contained bundle as a TypeScript string export so it
  //    imports directly into the app with no Metro asset config or runtime
  //    file loading. This is the most robust approach across dev/prod/EAS.
  ensureDir(OUT_DIR);
  const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
  const ts = `// AUTO-GENERATED by scripts/build-game.js — do not edit.\n// The full self-contained game build as a string. Loaded into the WebView.\nexport const GAME_HTML: string = \`\n${escaped}\n\`;\n`;
  fs.writeFileSync(OUT_FILE, ts, 'utf8');
  const kb = (fs.statSync(OUT_FILE).size / 1024).toFixed(1);
  log(`Wrote ${OUT_FILE} (${kb} KB)`);
  log('Done. The game is now bundled locally for the WebView.');
}

try {
  main();
} catch (err) {
  process.stderr.write(`[build-game] FAILED: ${err && err.message ? err.message : err}\n`);
  process.exit(1);
}
